version: '2'
services:
    onstock-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/onstock/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=onstock
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
